plugins {
    id 'com.android.application' version '8.13.2' apply true
}

android {
    defaultConfig {
        applicationId "com.Zombieschannel.Galaxy"
        versionCode 31
        versionName "0.3.1"

        externalNativeBuild {
            cmake {
                cppFlags ""
                arguments "-DANDROID_STL=c++_static"
                abiFilters 'armeabi-v7a', "arm64-v8a", "x86", "x86_64"
            }
        }
        targetSdk 37
        minSdk 21
    }
    packagingOptions {
        jniLibs {
            useLegacyPackaging = true
        }
    }

    splits {
        abi {
            enable true
            reset()
            include "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
            universalApk true
        }
    }

    buildTypes {
        release {
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
            externalNativeBuild {
                cmake {
                    cppFlags "-O2"
                }
            }
        }
        debug {
            externalNativeBuild {
                cmake {
                    cppFlags ""
                }
            }
            versionNameSuffix "-d"
            applicationIdSuffix '.debug'
        }
    }
    externalNativeBuild {
        cmake {
            path file('CMakeLists.txt')
        }
    }
    buildToolsVersion '35.0.0'
    ndkVersion '28.2.13676358'
    compileSdk 37
    namespace 'com.Zombieschannel.Galaxy'
    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            res {
                srcDirs 'res'
            }
            assets {
                srcDirs 'assets'
            }

        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
