#pragma once
#include <iostream>
#include <string>
#include <map>
#include <unordered_map>
#include <fstream>
#include <filesystem>
#include <chrono>
#include <vector>
using std::string;
using std::to_string;
using std::vector;
using std::cout;
using std::endl;
using std::ofstream;
using std::ifstream;
using std::ios;
using std::map;
using std::unordered_map;
using std::pair;
using std::unique_ptr;
using std::shared_ptr;
using std::weak_ptr;
using std::make_unique;
using std::stringstream;
using std::greater;
using std::min;
using std::max;
using std::array;
namespace filesystem = std::filesystem;
namespace chrono = std::chrono;